services:
  namechapdnsupdatev2:
    image: namechapdnsupdatev2
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - configuration=Debug
    environment:
      - intCheckTimerSEC=${intCheckTimerSEC:-300}
      - domain=${domain}
      - hosts=${hosts}
      - dynamicDNSPassword=${dynamicDNSPassword}
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
