services:
  namechapdnsupdatev2:
    image: namechapdnsupdatev2
    build:
      context: .
      dockerfile: ./dockerfile
    restart: unless-stopped
    environment:
      - intCheckTimerSEC=${intCheckTimerSEC:-300}
      - domain=${domain}
      - hosts=${hosts}
      - dynamicDNSPassword=${dynamicDNSPassword}
